spring:
  profiles:
    active: local-mysql
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=Asia/Seoul
    username: root
    password: kyeoneee1
    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
#      username: root
#      password: kyeoneee1
#      driver-class-name: com.mysql.jdbc.Driver
